defmodule Operator.Scene3dAssets do
  @moduledoc """
  The 3D models front screens can load by name in a `Mob.Scene3d` scene
  (`%Mob.Scene3d.IR.Model{asset: "d6.glb"}`): a d6, d12 and d20 die and a
  tabletop, from the rapier_lab demo (generated by its
  `priv/assets/dice_gen/build_dice.py`, with faces laid out for
  `MobRapier.Dice.face_up_d6/1` and friends).

  Embedded at build time, like `Operator.TzData` (`Application.app_dir/2`
  can't resolve priv/ on the device), written at boot to
  `<data dir>/scene3d_assets/` when missing or changed, and set as
  `mob_scene3d`'s asset root, so a relative asset name resolves there. An
  absolute path (a model the agent downloaded into its workspace) still
  works as is.
  """

  # credo:disable-for-next-line
  @dir Path.expand("../../priv/scene3d_assets", __DIR__)
  @names ~w(d6.glb d12.glb d20.glb table.glb)
  @assets (for name <- @names, into: %{} do
             path = Path.join(@dir, name)
             @external_resource path
             {name, File.read!(path)}
           end)

  @doc "The bundled models' names."
  @spec names() :: [String.t()]
  def names, do: @names

  @doc "Writes the models under `dir` and makes it mob_scene3d's asset root."
  @spec install!(Path.t()) :: :ok
  def install!(dir \\ Path.join(Operator.Paths.data_dir(), "scene3d_assets")) do
    File.mkdir_p!(dir)

    for {name, bytes} <- @assets do
      path = Path.join(dir, name)
      if File.read(path) != {:ok, bytes}, do: File.write!(path, bytes)
    end

    Application.put_env(:mob_scene3d, :asset_root, dir)
  end
end
