// mob_notify plugin — Android bridge (local notifications via AlarmManager,
// push registration and receipt via FirebaseMessaging).
//
// Extracted from mob-core's MobBridge notify_schedule / notify_cancel /
// notify_register_push (MobBridge.kt.eex ~1379-1444 pre-strip). Local
// notification DELIVERY stays in the host: its NotificationReceiver displays
// the scheduled notification and the tap routes through MainActivity. Push
// receipt ships HERE (MOB-327): MobFirebaseService (token refresh, messages
// that reach the app) and MobNotifyFcm (taps on notifications the system
// tray showed for FCM itself). The shared state lives in
// io.mob.plugin.MobNotifyHub (GENERATED by mob_dev next to MobActivityAware)
// — the stable seam both sides can reference, since this bridge can't name
// host-package classes and the host can't name plugin packages without
// breaking plugin-less builds.
//
// HOST-CLASS NAME ASSUMPTION: the alarm intent targets
// "<applicationId>.NotificationReceiver" via setClassName — true for every
// mob_new-generated app (the Kotlin package IS the applicationId). A host
// with a divergent package must keep its receiver at that name.
//
// BOOT RE-ARM: AlarmManager alarms are wiped on reboot, so scheduled
// notifications silently vanish. notify_schedule persists each schedule to
// SharedPreferences (via MobNotifySchedules), and MobNotifyBootReceiver
// re-arms every still-future entry on ACTION_BOOT_COMPLETED. The shared arm +
// persist + read logic lives in the MobNotifySchedules object so the bridge
// (which has an Activity) and the boot receiver (which has only a Context)
// arm identically — every helper takes a Context.
//
// SINGLE-FILE LAYOUT: MobNotifySchedules, MobNotifyBootReceiver, MobNotifyFcm,
// MobFcmEnvelope and MobFirebaseService are declared in THIS file rather than
// separate .kt files because mob_dev copies exactly the one `android.bridge_kt`
// path into the host Kotlin sourceSet (and the plugin signer only signs that
// one path) — sibling files wouldn't be compiled or signed. Kotlin allows
// multiple top-level declarations per file, so they all ship together under
// the declared bridge_kt; the plugin manifest's
// android.manifest_application_snippets declares the receiver and service.
package io.mob.notify

import android.app.Activity
import android.app.AlarmManager
import android.app.Application
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Bundle
import androidx.core.app.OnNewIntentProvider
import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage
import io.mob.plugin.MobNotifyHub
import java.lang.ref.WeakReference
import java.util.concurrent.atomic.AtomicBoolean
import org.json.JSONArray
import org.json.JSONObject

object MobNotifyBridge : io.mob.plugin.MobActivityAware {
    private var activityRef: WeakReference<Activity>? = null

    @JvmStatic external fun nativeRegister()

    // {:push_token, :android, token} — register_push's token, and refreshed
    // ones from MobFirebaseService.onNewToken.
    @JvmStatic external fun nativeDeliverNotifyPushToken(pid: Long, token: String)

    // A Mob.Notification JSON envelope, handed to core's
    // mob_deliver_notification (the :mob_screen router decodes it, or keeps it
    // until the router is up). pid is MobNotifyHub.notifyPid; 0 = none.
    @JvmStatic external fun nativeDeliverNotification(pid: Long, json: String)

    @JvmStatic fun register() = nativeRegister()

    override fun setActivity(activity: Activity) {
        activityRef = WeakReference(activity)
        MobNotifyFcm.attach(activity.application)
        MobNotifyFcm.watchNewIntents(activity)
    }

    // Parse the opts JSON and delegate to MobNotifySchedules.schedule, which
    // ensures the channel, arms an AlarmManager broadcast at trigger_at
    // targeting the HOST's NotificationReceiver (exact-alarm guard + inexact
    // fallback), AND persists the schedule to SharedPreferences so
    // MobNotifyBootReceiver can re-arm it after a reboot (alarms are wiped on
    // reboot). pid is accepted for zig-call parity; scheduling has no direct
    // reply.
    @JvmStatic
    fun notify_schedule(pid: Long, optsJson: String) {
        val activity = activityRef?.get() ?: return
        try {
            val opts = org.json.JSONObject(optsJson)
            val id = opts.getString("id")
            val title = opts.getString("title")
            val body = opts.getString("body")
            val triggerAt = opts.getLong("trigger_at") * 1000L // to ms
            val data = opts.optJSONObject("data")?.toString() ?: "{}"

            MobNotifySchedules.schedule(activity, id, triggerAt, title, body, data)
        } catch (e: Exception) {
            android.util.Log.e("MobNotify", "notify_schedule failed: ${e.message}")
        }
    }

    @JvmStatic
    fun notify_cancel(id: String) {
        val activity = activityRef?.get() ?: return
        MobNotifySchedules.cancel(activity, id)
    }

    // Registers the delivery target (the hub pid the host delivery paths key
    // on) and resolves the FCM token: a refresh that arrived while no screen
    // was registered is drained first; otherwise fetch fresh.
    @JvmStatic
    fun notify_register_push(pid: Long) {
        MobNotifyHub.notifyPid = pid
        MobNotifyHub.pendingToken?.let { token ->
            MobNotifyHub.pendingToken = null
            nativeDeliverNotifyPushToken(pid, token)
            return
        }
        com.google.firebase.messaging.FirebaseMessaging.getInstance().token
            .addOnCompleteListener { task ->
                if (task.isSuccessful) nativeDeliverNotifyPushToken(pid, task.result)
            }
    }
}

// Shared scheduling helpers — everything takes a Context so the bridge (passing
// its Activity) and MobNotifyBootReceiver (passing the receiver Context) build
// the PendingIntent, arm the alarm, and persist/read schedules identically.
object MobNotifySchedules {
    private const val PREFS = "mob_notify_schedules"
    private const val KEY = "schedules"

    // Build the broadcast PendingIntent the alarm fires — targets the HOST's
    // NotificationReceiver (which displays + handles tap), keyed by id.hashCode()
    // so notify_cancel / re-arm address the same alarm.
    private fun pendingIntent(ctx: Context, id: String, title: String, body: String, data: String): PendingIntent {
        val intent = Intent().apply {
            setClassName(ctx, ctx.packageName + ".NotificationReceiver")
            putExtra("title", title)
            putExtra("body", body)
            putExtra("id", id)
            putExtra("data", data)
        }
        return PendingIntent.getBroadcast(
            ctx, id.hashCode(), intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
    }

    // Also used by MobNotifyFcm for the banner of a push that arrives while
    // the app is open.
    fun ensureChannel(ctx: Context) {
        if (Build.VERSION.SDK_INT >= 26) {
            val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            nm.createNotificationChannel(
                NotificationChannel(MobNotifyHub.CHANNEL_ID, "Notifications", NotificationManager.IMPORTANCE_DEFAULT))
        }
    }

    // Arm the AlarmManager alarm with the exact-alarm guard + inexact fallback.
    // Android 12+ (API 31) gates EXACT alarms behind SCHEDULE_EXACT_ALARM special
    // access; calling setExact* without it throws SecurityException, so guard on
    // canScheduleExactAlarms() and fall back to an inexact (battery-batched) alarm.
    private fun arm(ctx: Context, triggerAtMs: Long, pi: PendingIntent) {
        val am = ctx.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        val canExact = if (Build.VERSION.SDK_INT >= 31) am.canScheduleExactAlarms() else true
        when {
            canExact && Build.VERSION.SDK_INT >= 23 ->
                am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAtMs, pi)

            canExact ->
                am.setExact(AlarmManager.RTC_WAKEUP, triggerAtMs, pi)

            Build.VERSION.SDK_INT >= 23 ->
                am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAtMs, pi)

            else ->
                am.set(AlarmManager.RTC_WAKEUP, triggerAtMs, pi)
        }
    }

    // Ensure the channel, arm the alarm, and persist the schedule so a reboot
    // can re-arm it. Used by notify_schedule and by the boot receiver's re-arm.
    fun schedule(ctx: Context, id: String, triggerAtMs: Long, title: String, body: String, data: String) {
        ensureChannel(ctx)
        arm(ctx, triggerAtMs, pendingIntent(ctx, id, title, body, data))
        persist(ctx, id, triggerAtMs, title, body, data)
    }

    // Cancel the alarm and drop the persisted entry.
    fun cancel(ctx: Context, id: String) {
        val intent = Intent().apply {
            setClassName(ctx, ctx.packageName + ".NotificationReceiver")
        }
        val pi = PendingIntent.getBroadcast(
            ctx, id.hashCode(), intent,
            PendingIntent.FLAG_NO_CREATE or PendingIntent.FLAG_IMMUTABLE)
        pi?.let {
            val am = ctx.getSystemService(Context.ALARM_SERVICE) as AlarmManager
            am.cancel(it)
        }
        remove(ctx, id)
    }

    // Re-arm every persisted schedule still in the future; drop past-due ones.
    // Called from MobNotifyBootReceiver on ACTION_BOOT_COMPLETED.
    fun rearmAll(ctx: Context) {
        val now = System.currentTimeMillis()
        for (s in readAll(ctx)) {
            val triggerAtMs = s.optLong("trigger_at_ms")
            val id = s.optString("id")
            if (triggerAtMs > now && id.isNotEmpty()) {
                ensureChannel(ctx)
                arm(ctx, triggerAtMs,
                    pendingIntent(ctx, id, s.optString("title"), s.optString("body"), s.optString("data", "{}")))
            } else {
                remove(ctx, id)
            }
        }
    }

    private fun prefs(ctx: Context) =
        ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    private fun readAll(ctx: Context): List<JSONObject> {
        val raw = prefs(ctx).getString(KEY, "[]") ?: "[]"
        val out = ArrayList<JSONObject>()
        try {
            val arr = JSONArray(raw)
            for (i in 0 until arr.length()) out.add(arr.getJSONObject(i))
        } catch (e: Exception) {
            android.util.Log.e("MobNotify", "readAll failed: ${e.message}")
        }
        return out
    }

    private fun writeAll(ctx: Context, entries: List<JSONObject>) {
        val arr = JSONArray()
        for (e in entries) arr.put(e)
        prefs(ctx).edit().putString(KEY, arr.toString()).apply()
    }

    // Upsert one schedule by id (one JSON array in one prefs key).
    private fun persist(ctx: Context, id: String, triggerAtMs: Long, title: String, body: String, data: String) {
        val entries = readAll(ctx).filterNot { it.optString("id") == id }.toMutableList()
        entries.add(JSONObject().apply {
            put("id", id)
            put("trigger_at_ms", triggerAtMs)
            put("title", title)
            put("body", body)
            put("data", data)
        })
        writeAll(ctx, entries)
    }

    private fun remove(ctx: Context, id: String) {
        writeAll(ctx, readAll(ctx).filterNot { it.optString("id") == id })
    }
}

// Boot re-arm receiver. On ACTION_BOOT_COMPLETED, re-arms persisted schedules
// (AlarmManager alarms are wiped on reboot). Declared in the host
// AndroidManifest by this plugin's android.manifest_application_snippets.
class MobNotifyBootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action == Intent.ACTION_BOOT_COMPLETED) {
            MobNotifySchedules.rearmAll(context)
        }
    }
}

// ── Push receipt (MOB-327) ─────────────────────────────────────────────────
//
// FCM reaches an app in three ways, and each becomes the Mob.Notification
// envelope core's mob_deliver_notification takes (mob's
// decisions/2026-10-01-notification-delivery-envelope.md):
//
//   * A message with a `notification` block while the app is in the
//     background: the system tray shows it and FCM never calls the app. The
//     tap launches the launcher activity with the message's data, plus FCM's
//     own `google.*` / `from` / `collapse_key` keys, as intent extras.
//     MobNotifyFcm reads them when that activity resumes (cold launch, or
//     onNewIntent + setIntent on a warm one) → presentation "tap". A tap that
//     carries mob_push's `mob_notification_json` is left to the host
//     MainActivity, which has always delivered those.
//   * Any message while the app is in the foreground, and a data-only message
//     in any state: MobFirebaseService.onMessageReceived. In the foreground →
//     presentation "foreground", plus a banner for a message with a
//     `notification` block (the system shows none for a foreground app),
//     whose tap carries `mob_notification_json` like a local notification's.
//     In the background a data-only message is a silent push: not a
//     notification, so not delivered (mob_wake's `mob_wake_id` messages go to
//     mob_wake in either state).
//   * A token refresh: MobFirebaseService.onNewToken → {:push_token, ...}.

// Builds the envelopes. Pure (org.json and the Kotlin stdlib only), so
// test/kotlin runs it on the host JVM.
object MobFcmEnvelope {
    const val MESSAGE_ID = "google.message_id"
    const val MOB_JSON = "mob_notification_json"

    // Keys FCM adds to a message's data bundle, and so to a tray tap's launch
    // extras; every other key is the sender's data.
    fun isReserved(key: String): Boolean =
        key.startsWith("google.") || key.startsWith("gcm.") ||
            key == "from" || key == "collapse_key" || key == MOB_JSON

    // A tray tap's message id and "tap" envelope, or null when the launch
    // extras are not a tap on a notification the system showed for FCM, or
    // carry mob_notification_json (which the host MainActivity delivers
    // itself). Decides on the two keys alone; only a tap reads `allExtras`,
    // so an ordinary resume doesn't copy every extra another app put on the
    // intent. The system strips the displayed title and body from the
    // extras, so the envelope has none.
    fun tap(
        messageId: String?,
        hasMobJson: Boolean,
        allExtras: () -> Map<String, Any?>,
    ): Pair<String, String>? {
        if (messageId.isNullOrEmpty() || hasMobJson) return null
        val data = LinkedHashMap<String, String?>()
        for ((key, value) in allExtras()) if (!isReserved(key)) data[key] = value?.toString()
        return messageId to build(messageId, null, null, data, "tap")
    }

    // The envelope for a message MobFirebaseService received: "foreground" for
    // the arrival, "tap" for the banner's content intent. mob_push's
    // mob_notification_json is the payload when present (its data map keeps
    // the types the server sent); the message id fills a missing id.
    fun fromMessage(
        messageId: String?,
        title: String?,
        body: String?,
        data: Map<String, String>,
        presentation: String,
    ): String {
        data[MOB_JSON]?.let { json ->
            try {
                val obj = JSONObject(json)
                if (!obj.has("id") && messageId != null) obj.put("id", messageId)
                obj.put("source", "push")
                obj.put("presentation", presentation)
                if (presentation == "tap") obj.put("action", "default") else obj.remove("action")
                return obj.toString()
            } catch (_: org.json.JSONException) {
                // Not an object: fall through to the message's own fields.
            }
        }
        return build(messageId, title, body, data.filterKeys { !isReserved(it) }, presentation)
    }

    private fun build(
        id: String?,
        title: String?,
        body: String?,
        data: Map<String, String?>,
        presentation: String,
    ): String {
        val dataObj = JSONObject()
        for ((key, value) in data) dataObj.put(key, value ?: JSONObject.NULL)
        return JSONObject().apply {
            if (id != null) put("id", id)
            if (title != null) put("title", title)
            if (body != null) put("body", body)
            put("source", "push")
            put("presentation", presentation)
            if (presentation == "tap") put("action", "default")
            put("data", dataObj)
        }.toString()
    }
}

// The Android half: tracks whether the app is in the foreground, delivers
// tray taps from the activity's intent (on resume, and on onNewIntent for a
// tap while the activity is already resumed), and shows the banner for a
// push that arrives in the foreground. attach() and watchNewIntents() run
// from MainActivity.onCreate (MobNotifyBridge.setActivity), before its
// onResume.
object MobNotifyFcm : Application.ActivityLifecycleCallbacks {
    private const val PREFS = "mob_notify_fcm"
    private const val TAPPED = "tapped_message_ids"
    private const val TAPPED_MAX = 32

    private val attached = AtomicBoolean(false)

    // Activities whose onNewIntent is already watched (weak: an activity is
    // dropped with its instance).
    private val watched = java.util.Collections.newSetFromMap(java.util.WeakHashMap<Activity, Boolean>())

    // Activities between onResume and onPause (main thread only).
    @Volatile private var resumed = 0

    val foreground: Boolean get() = resumed > 0

    fun attach(app: Application) {
        if (attached.compareAndSet(false, true)) app.registerActivityLifecycleCallbacks(this)
    }

    // A tray tap while the activity is already resumed (the user reopened the
    // app, then tapped the notification in the shade) reaches onNewIntent with
    // no onPause/onResume around it, so the resume check never sees it. Once
    // per activity instance; the persisted ids keep the later resume, which
    // sees the same intent through setIntent, from delivering it again.
    fun watchNewIntents(activity: Activity) {
        val provider = activity as? OnNewIntentProvider ?: return
        synchronized(watched) { if (!watched.add(activity)) return }
        provider.addOnNewIntentListener { intent -> deliverTap(activity, intent) }
    }

    override fun onActivityResumed(activity: Activity) {
        resumed += 1
        deliverTap(activity, activity.intent)
    }

    override fun onActivityPaused(activity: Activity) {
        resumed = maxOf(0, resumed - 1)
    }

    override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {}
    override fun onActivityStarted(activity: Activity) {}
    override fun onActivityStopped(activity: Activity) {}
    override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
    override fun onActivityDestroyed(activity: Activity) {}

    // An activity resumes with its launch intent many times (every return to
    // the app), and a re-created activity or a Recents relaunch replays it,
    // so each message id is delivered once. The ids persist because a replay
    // can come from a new process.
    private fun deliverTap(ctx: Context, intent: Intent?) {
        if (intent == null) return
        if ((intent.flags and Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY) != 0) return
        val tap = try {
            val bundle = intent.extras ?: return
            MobFcmEnvelope.tap(
                bundle.getString(MobFcmEnvelope.MESSAGE_ID),
                bundle.containsKey(MobFcmEnvelope.MOB_JSON),
            ) {
                @Suppress("DEPRECATION")
                bundle.keySet().associateWith { bundle.get(it) }
            }
        } catch (e: RuntimeException) {
            // Extras another app put on the intent can fail to unparcel
            // (BadParcelableException); that resume is not a tray tap.
            android.util.Log.w("MobNotify", "unreadable launch extras: $e")
            null
        } ?: return
        if (firstTap(ctx, tap.first)) deliver(tap.second)
    }

    @Synchronized
    private fun firstTap(ctx: Context, messageId: String): Boolean {
        val prefs = ctx.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val ids = try {
            JSONArray(prefs.getString(TAPPED, "[]"))
        } catch (_: org.json.JSONException) {
            JSONArray()
        }
        for (i in 0 until ids.length()) if (ids.optString(i) == messageId) return false
        ids.put(messageId)
        while (ids.length() > TAPPED_MAX) ids.remove(0)
        prefs.edit().putString(TAPPED, ids.toString()).apply()
        return true
    }

    // False when the native library isn't loaded: Android started the process
    // for MobFirebaseService alone, so there is no BEAM to deliver to.
    fun deliver(json: String): Boolean = nativeCall {
        MobNotifyBridge.nativeDeliverNotification(MobNotifyHub.notifyPid, json)
    }

    fun nativeCall(call: () -> Unit): Boolean =
        try {
            call()
            true
        } catch (_: UnsatisfiedLinkError) {
            false
        }

    // The banner the system would have shown had the app been in the
    // background. Its tap opens the launcher activity by component (a
    // MAIN/LAUNCHER intent would only bring an existing task forward without
    // onNewIntent) with mob_notification_json, which the host MainActivity
    // delivers as a tap, the same way as a local notification's.
    fun showBanner(ctx: Context, message: RemoteMessage, notif: RemoteMessage.Notification) {
        val component = ctx.packageManager.getLaunchIntentForPackage(ctx.packageName)?.component ?: return
        val json = MobFcmEnvelope.fromMessage(message.messageId, notif.title, notif.body, message.data, "tap")
        val code = (message.messageId ?: json).hashCode()
        val tap = Intent().apply {
            setComponent(component)
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP
            putExtra(MobFcmEnvelope.MOB_JSON, json)
        }
        val contentPi = PendingIntent.getActivity(
            ctx, code, tap, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)

        val nm = ctx.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        val builder = if (Build.VERSION.SDK_INT >= 26) {
            // The sender's channel when the app created it; otherwise mob_notify's.
            val channel = notif.channelId?.takeIf { nm.getNotificationChannel(it) != null }
                ?: MobNotifyHub.CHANNEL_ID.also { MobNotifySchedules.ensureChannel(ctx) }
            Notification.Builder(ctx, channel)
        } else {
            @Suppress("DEPRECATION")
            Notification.Builder(ctx)
        }
        val banner = builder
            .setSmallIcon(android.R.drawable.ic_dialog_info)
            .setContentTitle(notif.title ?: "")
            .setContentText(notif.body ?: "")
            .setContentIntent(contentPi)
            .setAutoCancel(true)
            .build()
        nm.notify(code, banner)
    }

    // mob_wake owns silent pushes (`mob_wake_id`) and wants the FCM token
    // too. Android hands FCM to one service, so this one forwards to mob_wake
    // when the app has it; reflection keeps apps without mob_wake compiling.
    // False when mob_wake isn't in the app.
    fun forwardToMobWake(method: String, vararg args: String): Boolean {
        val cls = try {
            Class.forName("io.mob.wake.MobWakeBridge")
        } catch (_: ClassNotFoundException) {
            return false
        }
        try {
            cls.getMethod(method, *Array(args.size) { String::class.java }).invoke(null, *args)
        } catch (e: ReflectiveOperationException) {
            // Typically UnsatisfiedLinkError inside: no BEAM in this process.
            android.util.Log.w("MobNotify", "mob_wake $method failed: ${e.cause ?: e}")
        }
        return true
    }
}

// The app's FirebaseMessagingService, declared by this plugin's
// android.manifest_application_snippets at intent-filter priority -1: an app
// that declares its own MESSAGING_EVENT service (priority 0) keeps receiving
// FCM, and this one stands by. See the comment above MobFcmEnvelope.
class MobFirebaseService : FirebaseMessagingService() {

    // Straight to the process that called MobNotify.register_push/1 when one
    // did; otherwise parked for register_push to drain.
    override fun onNewToken(token: String) {
        val pid = MobNotifyHub.notifyPid
        val delivered = pid != 0L &&
            MobNotifyFcm.nativeCall { MobNotifyBridge.nativeDeliverNotifyPushToken(pid, token) }
        if (!delivered) MobNotifyHub.pendingToken = token
        MobNotifyFcm.forwardToMobWake("onFcmTokenRefresh", token)
    }

    override fun onMessageReceived(message: RemoteMessage) {
        val data = message.data
        data["mob_wake_id"]?.let { identifier ->
            if (MobNotifyFcm.forwardToMobWake("onPushFired", identifier, JSONObject(data as Map<*, *>).toString())) return
        }
        // The banner whenever a notification block reaches the app (Android
        // displays it itself only for a background app), like the host's
        // NotificationReceiver; the arrival only while an activity is resumed.
        val notif = message.notification
        if (MobNotifyFcm.foreground) {
            MobNotifyFcm.deliver(
                MobFcmEnvelope.fromMessage(message.messageId, notif?.title, notif?.body, data, "foreground"))
        }
        if (notif != null) MobNotifyFcm.showBanner(this, message, notif)
    }
}
